base_url = "https://kb-98b.pages.dev"
title = "KendoZoBlo"
description = "Kendo's Zolla Blog"
theme="lightspeed"
compile_sass = true
generate_feed = true

highlight_code = true
highlight_theme = "1337"

[extra]

seo = true
author = "Kendofriendo"
ogimage = "lightning.png"

zola = true
netlify = false
maintained_with_love = false

footer_links = [
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/atom.xml", name = "RSS"},
    {url = "https://github.com/kendofriendo/kb", name = "Source on Github"},
]

